### ISSUE TITLE
Translation doesnt seem to be working??

### ISSUE THREAD

**Issue by armst297** [karansher/computer-graphics-shader-pipeline#13]
![image](https://user-images.githubusercontent.com/23227122/202575455-3207ec35-1d9b-4996-9c09-4b247f68ca5f.png)
Image 1: Only scale the moon by 0.3 and translate the moon 2,0,2 (2 in x and z)
![image](https://user-images.githubusercontent.com/23227122/202575460-14ef24c6-ae7d-402e-ad26-6725d10c8351.png)
Image 1: Only scale the moon by 0.3 and translate the moon 3,0,3 (3 in x and z)

I am using the translation matrix from class but in 3 dimensions.
![image](https://user-images.githubusercontent.com/23227122/202575770-b62be7f3-a2eb-4cc5-9fda-4a19f5647886.png)

My code for the model_projection follows the following format:
1. use the given conversion to a vec3 to a vec4
2. multiply by the model (LHS)
3. multiply by the view matrix (LHS)
4. multiply by the proj matrix (LHS)

How can I debug this? It doesn't make sense that it would show up like this.

**Comment by kevin-j-wang** [comment]
i dont know if this is your issue but when i had this issue that was because my matrix columns and rows were switched. in opengl, writing 
(abcd
efgh
ijkl
mnop), the abcd is the column, not aeim like youd expect.

**Comment by armst297** [comment]
Thanks this fixed it!
