### ISSUE TITLE
Perlin noise is non-continous on certain axes?

### ISSUE THREAD

**Issue by DerekCresswell** [karansher/computer-graphics-shader-pipeline#15]
![image](https://user-images.githubusercontent.com/44453572/202588479-c1e4c3e8-51c2-400f-ad69-01b4eaa76d59.png)

It appears that my perlin noise is not continuous on the y and z axes, but is on the x. I'm fairly sure I've followed the algorithm to a T. I've been playing around with different values, swapping orders, etc. But they only affect the noise shown, nothing moves or fixes these borders.

Any idea for what might be the cause of this?

**Comment by JanardanS** [comment]
are u using floor or int when you set the boxes? Because I think I've seen this error because rather than using the floor, int will not properly clamp it to negative integers, which might be the issue.

**Comment by DerekCresswell** [comment]
No, it turned out to be that I was interpolating in the wrong order. I had thought that order didn't matter. It's important that you only interpolate between one coordinate at a time.
